### ISSUE TITLE
Running "train" throws an error

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/stodt#4]
```shell
$ ./run train 2
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    x_train, y_train, x_test, y_test = loader.load(X, Y)
  File "/app/modules/loader.py", line 72, in load
    validation_X_B, validation_Y_B = self.timeshifted_timeseries(X, Y, i + training_records, validation_timeseries)
  File "/app/modules/loader.py", line 25, in timeshifted_timeseries
    timeseries_X = np.reshape(np.stack(timeseries_X), (-1, self.time_series_length, X.shape[1]))
  File "<__array_function__ internals>", line 6, in stack
  File "/usr/local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

**Comment by Piiit** [comment]
@giacomo-montibeller This bug still exists with the new version... could you please have a look?

**Comment by giacomo-montibeller** [comment]
you need to attempt the training on at least some days of data because it can happen that you downloaded days where required data weren't collected by the stations.

**Comment by Piiit** [comment]
@giacomo-montibeller That is fine, but the error reporting should explain that and give a hint on how to fix that, or that the data provided did not contain such information... the more details the better. Just throwing an exception makes people think it is a bug and not a known issue.
