### ISSUE TITLE
RuntimeError: Invalid date during "./run app"

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/stodt#8]
When I run the `app` and open http://0.0.0.0:5000/, it gives the following error:

```shell
$ ./run app
.........
[2020-03-04 13:37:19,774] ERROR in app: Exception on /history [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 52, in history
    labels, outputs, timestamps = _predict_dates(days, predicter)
  File "/app/app.py", line 68, in _predict_dates
    timestamps, labels, outputs = predicter.predict(days)
  File "/app/modules/predict.py", line 37, in predict
    tmpX, tmpY = loader.a_timeseries_before(numpy_features, numpy_labels, date.timestamp(), self.time_frame_size)
  File "/app/modules/loader.py", line 34, in a_timeseries_before
    raise RuntimeError("Invalid date")
RuntimeError: Invalid date
172.17.0.1 - - [04/Mar/2020 13:37:19] "GET /history?start=2020-02-29&end=2020-03-04 HTTP/1.1" 500 -
```

**Comment by giacomo-montibeller** [comment]
As you can see `RuntimeError: Invalid date
172.17.0.1 - - [04/Mar/2020 13:37:19] "GET /history?start=2020-02-29&end=2020-03-04 HTTP/1.1" 500 -` the problem can be that you attempted to see history of days that you haven't downloaded (between 2020-02-29 and 2020-03-04).

Example: if you want to predict 2020-03-04, you must have the previous day's data because the network need that data to do the regression. This argument is extended to the history problem (which is just n predictions inlined).
